name: todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.5

dependencies:
  device_calendar_plus: ^0.10.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^22.3.1
  home_widget: ^0.10.0
  path: ^1.9.1
  path_provider: ^2.1.6
  timezone: ^0.11.1
  todo_core:
    path: ../../packages/core
  workmanager: ^0.10.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
